spring.application.name=mssc-beer-inventory-service
logging.level.guru=debug
server.port=8082
spring.profiles.active=localmysql,local-discovery
spring.artemis.user=artemis
spring.artemis.password=simetraehcapa

logging.level.guru.sfg=DEBUG